name: PetsPlus
author: AlexProgrammerDE
version: 1.0
main: me.alexprogrammerde.petsplus.Main
description: More options for all pets!
api-version: 1.15
softdepend: [PlaceholderAPI, Vault]
commands:
  pets:
permissions:
  petsplus.*:
    children:
      petsplus.admin: true
      petsplus.player: true
  petsplus.admin:
    default: false
  petsplus.player:
    default: true